import "../globals.css";
import Sidebar from "./components/sidebar/Sidebar";

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="admin-layout">
          <aside className="admin-sidebar">
            <Sidebar />
          </aside>

          <div className="admin-main-wrapper">
            <main className="admin-content-area">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}