import { AuthProvider } from "../context/AuthContext";
import { GlobalProvider } from "../context/GlobalContext";
import "../globals.css";
import Sidebar from "./components/sidebar/Sidebar";

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <GlobalProvider>
            <div className="admin-layout">
              <aside className="admin-sidebar">
                <Sidebar />
              </aside>

              <div className="admin-main-wrapper">
                <main className="admin-content-area">
                  {children}
                </main>
              </div>
            </div>
          </GlobalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}