// constants.js
export const INITIAL_MEDICINES = [
  {
    id: 1,
    name: "Invokana 100mg Tablet",
    vendor: "Johnson & Johnson Ltd",
    actualPrice: 545,
    discountPrice: 463,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",

    introduction: "Invokana 100mg Tablet is used to control high blood sugar levels in patients with type 2 diabetes.",
    description: "It works by helping the kidneys remove excess glucose from the bloodstream through urine.",
    useOfMedicine: ["Type 2 Diabetes", "Blood sugar control"],
    drugCategory: "SGLT2 Inhibitor",
    sideEffects: ["Frequent urination", "Dehydration", "Dizziness", "Urinary tract infection"],
    safetyAdvice: "Use with caution in kidney disease patients. Avoid excessive alcohol consumption.",
    saltComposition: "Canagliflozin 100mg",
    primaryUse: "Treatment of Type 2 Diabetes Mellitus",
    saltSynonyms: ["Canagliflozin"],
    storage: "Store below 30°C in a dry place away from sunlight.",
    benefits: ["Improves blood sugar control", "Supports heart health", "May help in weight reduction"],
    howToUse: "Take once daily before the first meal of the day as prescribed by your doctor."
  },

  {
    id: 2,
    name: "Metformin 500mg Tablet",
    vendor: "Sun Pharma Ltd",
    actualPrice: 120,
    discountPrice: 95,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=400&q=80",

    introduction: "Metformin 500mg is an oral anti-diabetic medicine.",
    description: "It lowers glucose production in the liver and improves insulin sensitivity.",
    useOfMedicine: ["Type 2 Diabetes", "PCOS"],
    drugCategory: "Biguanide",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal pain"],
    safetyAdvice: "Avoid alcohol. Inform doctor if you have kidney or liver issues.",
    saltComposition: "Metformin Hydrochloride 500mg",
    primaryUse: "Control of blood sugar",
    saltSynonyms: ["Metformin HCl"],
    storage: "Store at room temperature.",
    benefits: ["Reduces blood glucose", "Improves insulin response"],
    howToUse: "Take with food to reduce stomach upset."
  },

  {
    id: 3,
    name: "Augmentin 625mg Tablet",
    vendor: "GlaxoSmithKline",
    actualPrice: 210,
    discountPrice: 185,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=400&q=80",

    introduction: "Augmentin is an antibiotic used to treat bacterial infections.",
    description: "It contains Amoxicillin and Clavulanic Acid which fight bacteria.",
    useOfMedicine: ["Respiratory infection", "Urinary tract infection", "Skin infection"],
    drugCategory: "Penicillin Antibiotic",
    sideEffects: ["Diarrhea", "Rash", "Nausea"],
    safetyAdvice: "Complete the full course. Avoid if allergic to penicillin.",
    saltComposition: "Amoxicillin 500mg + Clavulanic Acid 125mg",
    primaryUse: "Bacterial infections",
    saltSynonyms: ["Co-amoxiclav"],
    storage: "Store below 25°C.",
    benefits: ["Effective against resistant bacteria"],
    howToUse: "Take after meals with water."
  },

  {
    id: 4,
    name: "Dolo 650 Tablet",
    vendor: "Micro Labs Ltd",
    actualPrice: 35,
    discountPrice: 30,
    image: "https://images.unsplash.com/photo-1588776814546-ec7e2b57c2d6?auto=format&fit=crop&w=400&q=80",

    introduction: "Dolo 650 is used to relieve pain and fever.",
    description: "It contains Paracetamol which reduces fever and mild to moderate pain.",
    useOfMedicine: ["Fever", "Headache", "Body pain"],
    drugCategory: "Analgesic & Antipyretic",
    sideEffects: ["Allergic reaction (rare)", "Liver damage (overdose)"],
    safetyAdvice: "Do not exceed recommended dose.",
    saltComposition: "Paracetamol 650mg",
    primaryUse: "Pain and fever relief",
    saltSynonyms: ["Acetaminophen"],
    storage: "Keep in a cool dry place.",
    benefits: ["Quick fever reduction", "Safe when used correctly"],
    howToUse: "Take after food with water."
  },

  {
    id: 5,
    name: "Amlodipine 5mg Tablet",
    vendor: "Cipla Ltd",
    actualPrice: 90,
    discountPrice: 72,
    image: "https://images.unsplash.com/photo-1580281658629-58c4e4dba9c9?auto=format&fit=crop&w=400&q=80",

    introduction: "Amlodipine is used to treat high blood pressure.",
    description: "It relaxes blood vessels and improves blood flow.",
    useOfMedicine: ["Hypertension", "Angina"],
    drugCategory: "Calcium Channel Blocker",
    sideEffects: ["Swelling of ankles", "Headache", "Dizziness"],
    safetyAdvice: "Monitor blood pressure regularly.",
    saltComposition: "Amlodipine 5mg",
    primaryUse: "High blood pressure treatment",
    saltSynonyms: ["Amlodipine Besylate"],
    storage: "Store below 30°C.",
    benefits: ["Prevents heart attack & stroke risk"],
    howToUse: "Take once daily at the same time."
  },

  // 6 to 15 (Shortened for space but complete structure)

  {
    id: 6,
    name: "Atorvastatin 10mg",
    vendor: "Dr Reddy's Labs",
    actualPrice: 150,
    discountPrice: 120,
    image: "https://images.unsplash.com/photo-1576765607924-3f0c2d6b7c10?auto=format&fit=crop&w=400&q=80",
    introduction: "Used to lower cholesterol levels.",
    description: "Reduces bad cholesterol and triglycerides.",
    useOfMedicine: ["High cholesterol"],
    drugCategory: "Statin",
    sideEffects: ["Muscle pain", "Nausea"],
    safetyAdvice: "Avoid grapefruit juice.",
    saltComposition: "Atorvastatin 10mg",
    primaryUse: "Cholesterol management",
    saltSynonyms: ["Atorva"],
    storage: "Room temperature.",
    benefits: ["Reduces heart disease risk"],
    howToUse: "Take once daily."
  },

  {
    id: 7,
    name: "Pantoprazole 40mg",
    vendor: "Lupin Ltd",
    actualPrice: 110,
    discountPrice: 85,
    image: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=400&q=80",
    introduction: "Used for acidity and GERD.",
    description: "Reduces stomach acid production.",
    useOfMedicine: ["Acidity", "GERD"],
    drugCategory: "Proton Pump Inhibitor",
    sideEffects: ["Headache", "Diarrhea"],
    safetyAdvice: "Take before food.",
    saltComposition: "Pantoprazole 40mg",
    primaryUse: "Acid reflux treatment",
    saltSynonyms: ["Pantoprazole Sodium"],
    storage: "Store below 25°C.",
    benefits: ["Relieves heartburn"],
    howToUse: "Take 30 minutes before breakfast."
  },

  {
    id: 8,
    name: "Levocetirizine 5mg",
    vendor: "Alkem Labs",
    actualPrice: 75,
    discountPrice: 60,
    image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=400&q=80",
    introduction: "Anti-allergy medication.",
    description: "Relieves sneezing and runny nose.",
    useOfMedicine: ["Allergic rhinitis", "Skin allergy"],
    drugCategory: "Antihistamine",
    sideEffects: ["Drowsiness", "Dry mouth"],
    safetyAdvice: "Avoid driving after taking.",
    saltComposition: "Levocetirizine 5mg",
    primaryUse: "Allergy relief",
    saltSynonyms: ["Levocet"],
    storage: "Room temperature.",
    benefits: ["Fast allergy relief"],
    howToUse: "Take once daily in evening."
  },

  {
    id: 9,
    name: "Azithromycin 500mg",
    vendor: "Pfizer Ltd",
    actualPrice: 180,
    discountPrice: 150,
    image: "https://images.unsplash.com/photo-1581595219341-7a5d2e0b8c9e?auto=format&fit=crop&w=400&q=80",
    introduction: "Antibiotic for bacterial infections.",
    description: "Stops bacterial growth.",
    useOfMedicine: ["Respiratory infection", "Skin infection"],
    drugCategory: "Macrolide Antibiotic",
    sideEffects: ["Nausea", "Abdominal pain"],
    safetyAdvice: "Complete full course.",
    saltComposition: "Azithromycin 500mg",
    primaryUse: "Bacterial infection treatment",
    saltSynonyms: ["Azi"],
    storage: "Store below 30°C.",
    benefits: ["Effective short course antibiotic"],
    howToUse: "Take once daily before food."
  },

  {
    id: 10,
    name: "Montelukast 10mg",
    vendor: "Cipla Ltd",
    actualPrice: 140,
    discountPrice: 110,
    image: "https://images.unsplash.com/photo-1588776814546-ec7e2b57c2d6?auto=format&fit=crop&w=400&q=80",
    introduction: "Used for asthma and allergies.",
    description: "Reduces airway inflammation.",
    useOfMedicine: ["Asthma", "Allergy"],
    drugCategory: "Leukotriene Receptor Antagonist",
    sideEffects: ["Headache", "Mood changes"],
    safetyAdvice: "Take at night.",
    saltComposition: "Montelukast 10mg",
    primaryUse: "Asthma prevention",
    saltSynonyms: ["Montair"],
    storage: "Room temperature.",
    benefits: ["Prevents asthma attacks"],
    howToUse: "Take once daily."
  },

  {
    id: 11,
    name: "Losartan 50mg",
    vendor: "Sun Pharma",
    actualPrice: 130,
    discountPrice: 100,
    image: "https://images.unsplash.com/photo-1580281657521-6b6b2c8b8f6c?auto=format&fit=crop&w=400&q=80",
    introduction: "Treats high blood pressure.",
    description: "Relaxes blood vessels.",
    useOfMedicine: ["Hypertension"],
    drugCategory: "ARB",
    sideEffects: ["Dizziness"],
    safetyAdvice: "Monitor BP regularly.",
    saltComposition: "Losartan 50mg",
    primaryUse: "Blood pressure control",
    saltSynonyms: ["Losar"],
    storage: "Below 30°C.",
    benefits: ["Prevents stroke risk"],
    howToUse: "Take once daily."
  },

  {
    id: 12,
    name: "Glimepiride 2mg",
    vendor: "Torrent Pharma",
    actualPrice: 85,
    discountPrice: 65,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    introduction: "Oral anti-diabetic drug.",
    description: "Stimulates insulin release.",
    useOfMedicine: ["Type 2 Diabetes"],
    drugCategory: "Sulfonylurea",
    sideEffects: ["Low blood sugar"],
    safetyAdvice: "Eat properly after taking.",
    saltComposition: "Glimepiride 2mg",
    primaryUse: "Blood sugar control",
    saltSynonyms: ["Amaryl"],
    storage: "Room temperature.",
    benefits: ["Controls post-meal sugar"],
    howToUse: "Take before breakfast."
  },

  {
    id: 13,
    name: "Cetirizine 10mg",
    vendor: "Zydus Cadila",
    actualPrice: 50,
    discountPrice: 40,
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=400&q=80",
    introduction: "Allergy relief tablet.",
    description: "Blocks histamine effects.",
    useOfMedicine: ["Allergy"],
    drugCategory: "Antihistamine",
    sideEffects: ["Drowsiness"],
    safetyAdvice: "Avoid driving.",
    saltComposition: "Cetirizine 10mg",
    primaryUse: "Allergy treatment",
    saltSynonyms: ["Cetzine"],
    storage: "Room temperature.",
    benefits: ["Reduces sneezing"],
    howToUse: "Take once daily."
  },

  {
    id: 14,
    name: "Clopidogrel 75mg",
    vendor: "Intas Pharma",
    actualPrice: 160,
    discountPrice: 135,
    image: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=400&q=80",
    introduction: "Prevents blood clots.",
    description: "Prevents platelets from sticking together.",
    useOfMedicine: ["Heart attack prevention"],
    drugCategory: "Antiplatelet",
    sideEffects: ["Bleeding"],
    safetyAdvice: "Avoid injury.",
    saltComposition: "Clopidogrel 75mg",
    primaryUse: "Clot prevention",
    saltSynonyms: ["Clopilet"],
    storage: "Below 30°C.",
    benefits: ["Reduces stroke risk"],
    howToUse: "Take once daily."
  },

  {
    id: 15,
    name: "Rabeprazole 20mg",
    vendor: "Cadila Healthcare",
    actualPrice: 125,
    discountPrice: 98,
    image: "https://images.unsplash.com/photo-1576765607924-3f0c2d6b7c10?auto=format&fit=crop&w=400&q=80",
    introduction: "Treats acidity and ulcers.",
    description: "Reduces stomach acid.",
    useOfMedicine: ["Acidity", "Ulcer"],
    drugCategory: "Proton Pump Inhibitor",
    sideEffects: ["Headache"],
    safetyAdvice: "Take before meals.",
    saltComposition: "Rabeprazole 20mg",
    primaryUse: "Acid control",
    saltSynonyms: ["Rablet"],
    storage: "Room temperature.",
    benefits: ["Relieves heartburn"],
    howToUse: "Take before breakfast."
  }
];