import { AuthProvider } from "../context/AuthContext";
import { GlobalProvider } from "../context/GlobalContext";
import "../globals.css";
import Footer from "./components/Footer";
import GlobalModal from "./components/GlobalModal";
import TopNavbar from "./components/TopNavbar";

export const metadata = {
  title: "Home Health Kangaroo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider >
          <GlobalProvider>
            <TopNavbar />
            {children}
            <Footer />
            <GlobalModal />
          </GlobalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
