import { AuthProvider } from "../context/AuthContext";
import { GlobalProvider } from "../context/GlobalContext";
import { UserProvider } from "../context/UserContext";
import "../globals.css";
import Footer from "./components/Footer";
import GlobalModal from "./components/GlobalModal";
import TopNavbar from "./components/TopNavbar";

export const metadata = {
  title: "Home Health Kangaroo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider >
          <UserProvider >
            <GlobalProvider>
              <TopNavbar />
              {children}
              <Footer />
              <GlobalModal />
            </GlobalProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
